In [1]:
pip install XGBoost

Requirement already satisfied: XGBoost in c:\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from XGBoost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from XGBoost) (1.16.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import XGBoost

ModuleNotFoundError: No module named 'XGBoost'

In [3]:
import xgboost

In [4]:
import pandas as pd

In [5]:
dataset=pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [11]:
# split training set 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [44]:
#regressor=xgboost.XGBRegressor()
regressor=xgboost.XGBRegressor(n_estimators=50,max_depth=2,random_state=0)

In [45]:
regressor.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=30,
             n_jobs=None, num_parallel_tree=None, ...)

In [46]:
y_predict=regressor.predict(x_test)

In [47]:
# r2evaluation
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)

In [48]:
r_score

0.8917367458343506

In [50]:
# saving the model
import pickle
filename="XGBoostAlgorithm.sav"

In [51]:
pickle.dump(regressor,open(filename,"wb"))

In [52]:
load_model=pickle.load(open("XGBoostAlgorithm.sav","rb"))

In [54]:
result=load_model.predict([[25,45,2,1,0]])

In [55]:
result

array([5073.329], dtype=float32)